# Generated by Django 5.0.7 on 2025-12-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAccountMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('account_id', models.UUIDField(db_index=True)),
                ('account_name', models.CharField(max_length=255)),
                ('total_activities', models.IntegerField(default=0)),
                ('calls_count', models.IntegerField(default=0)),
                ('emails_count', models.IntegerField(default=0)),
                ('meetings_count', models.IntegerField(default=0)),
                ('active_projects', models.IntegerField(default=0)),
                ('total_contract_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'daily_account_metrics',
                'ordering': ['-date', 'account_name'],
                'indexes': [models.Index(fields=['date', 'account_id'], name='daily_accou_date_4ea969_idx')],
                'unique_together': {('date', 'account_id')},
            },
        ),
        migrations.CreateModel(
            name='EventCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('aggregate_type', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'event_counts',
                'ordering': ['-date', 'event_type'],
                'unique_together': {('date', 'event_type', 'aggregate_type')},
            },
        ),
        migrations.CreateModel(
            name='LeadFunnelMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('new_leads', models.IntegerField(default=0)),
                ('contacted_leads', models.IntegerField(default=0)),
                ('qualified_leads', models.IntegerField(default=0)),
                ('won_leads', models.IntegerField(default=0)),
                ('lost_leads', models.IntegerField(default=0)),
                ('total_estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('won_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lost_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lead_funnel_metrics',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='RevenueMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(db_index=True)),
                ('account_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contracted_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('projects_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'revenue_metrics',
                'ordering': ['-month', 'account_name'],
                'unique_together': {('month', 'account_id')},
            },
        ),
    ]
