# Generated by Django 5.0.7 on 2025-12-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('aggregate_type', models.CharField(max_length=50)),
                ('aggregate_id', models.UUIDField()),
                ('payload', models.JSONField()),
                ('error_message', models.TextField()),
                ('error_trace', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField()),
                ('first_failed_at', models.DateTimeField(auto_now_add=True)),
                ('last_failed_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'failed_events',
                'ordering': ['-first_failed_at'],
                'indexes': [models.Index(fields=['event_type'], name='failed_even_event_t_814e31_idx'), models.Index(fields=['resolved_at'], name='failed_even_resolve_0d7fe2_idx'), models.Index(fields=['-first_failed_at'], name='failed_even_first_f_6c421b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('aggregate_type', models.CharField(max_length=50)),
                ('aggregate_id', models.UUIDField()),
                ('processed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'processed_events',
                'ordering': ['-processed_at'],
                'indexes': [models.Index(fields=['event_id'], name='processed_e_event_i_5c8b00_idx'), models.Index(fields=['processed_at'], name='processed_e_process_263057_idx'), models.Index(fields=['aggregate_type', 'aggregate_id'], name='processed_e_aggrega_8e3518_idx')],
            },
        ),
    ]
